[package]
name = "wgpu-info"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = "A tool to print and process information about available wgpu adapters."
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
# Enable the wasm-bindgen code path outside of wasm32.
wasm-bindgen = ["wgpu/wasm-bindgen"]

[dependencies]
anyhow.workspace = true
bitflags.workspace = true
env_logger.workspace = true
hashbrown = { workspace = true, features = ["serde"] }
pico-args.workspace = true
pollster.workspace = true
serde = { workspace = true, features = ["default"] }
serde_json.workspace = true
wgpu.workspace = true

[lints.clippy]
disallowed_types = "allow"
