[package]
name = "naga-xtask"
version = "0.1.0"
edition = "2021"
publish = false
rust-version.workspace = true

[features]
# Enable the wasm-bindgen code path outside of wasm32.
wasm-bindgen = []

[target.'cfg(not(any(target_arch = "wasm32", feature = "wasm-bindgen")))'.dependencies]
anyhow.workspace = true
env_logger = { workspace = true, default-features = false }
glob.workspace = true
hlsl-snapshots.workspace = true
indicatif.workspace = true
jobserver.workspace = true
log.workspace = true
num_cpus.workspace = true
pico-args.workspace = true
shell-words.workspace = true
which.workspace = true
